version: 0.0
os: linux
files:
  - source: /
    destination: /application
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  Install:
    - location: scripts/aws/install.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/aws/application_start.sh
      timeout: 60
      runas: ec2-user
  ApplicationStop:
    - location: scripts/aws/stop_server.sh
      timeout: 60
      runas: ec2-user
