version: 0.2

phases:
  install:
    commands:
      - echo 'Run npm install'
      - cd ./react-front-end
      - npm install
      - cd ../express-back-end
      - npm install
      - cd ..
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - cd ./react-front-end
      - npm run build
      - cd ..
  post_build:
    commands:
      - echo Build completed on `date`
      - mv ./react-front-end/build ./express-back-end/
      - mv ./express-back-end/build/ ./express-back-end/public
artifacts:
  files:
    - './express-back-end/**'
