version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm run client:install
  build:
    commands:
      - npm run server:build
      - npm run client:build
  post_build:
    commands:
      - rm -rf src/client/node_modules
artifacts:
  files:
    - "**/*"
